version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes: 
      - ./datadir:/data/db/

  mongo_seed:
    image: mongo
    links:
      - mongo
    volumes: 
      - ./mongo_seed:/mongo_seed
    command: 
      /mongo_seed/import.sh

  identity-server:
    build: 
      context: ./src/Exadel.CrazyPrice
      dockerfile: Exadel.CrazyPrice.IdentityServer/Dockerfile
    ports:
      - '8000:80'
      - '8001:443'
    volumes:
      - ./logs/identityServer:/app/Logs/
      - ./src/Exadel.CrazyPrice/Exadel.CrazyPrice.IdentityServer:/root/IdentityServer:cached
      - type: bind
        source: ./certs/aspnetapp-root-cert.cer
        target: /https-root/aspnetapp-root-cert.cer
      - type: bind
        source: ./certs/aspnetapp-identity-server.pfx
        target: /https/aspnetapp-identity-server.pfx
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp-identity-server.pfx

  web-api:
    build:
      context: ./src/Exadel.CrazyPrice
      dockerfile: Exadel.CrazyPrice.WebApi/Dockerfile
    ports:
      - '9000:80'
      - '9001:443'
    volumes:
      - ./logs/api:/app/Logs/
      - ./src/Exadel.CrazyPrice/Exadel.CrazyPrice.WebApi:/root/Api:cached
      - type: bind
        source: ./certs/aspnetapp-web-api.pfx
        target: /https/aspnetapp-web-api.pfx
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=9001
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp-web-api.pfx