version: '3.8'

services:
 database:
  image: mongo:4.4.4
  ports:
   - 27017:27017
  restart: always
  volumes:
   - ./volumes/database/data:/data/db/

 databaseseed:
  image: mongo
  links:
   - database
  volumes:
   - ./volumes/database/seed:/seed/
  command:
   /seed/import.sh
  depends_on:
   - database

 cprabbit:
  image: rabbitmq:3-management
  ports:
   - 5672:5672
   - 15672:15672
  restart: always
  volumes:
   - ./volumes/configuration/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
   - ./volumes/configuration/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
   - ./volumes/rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@cprabbit
   - ./volumes/logs/rabbitmq:/var/log/rabbitmq/log

 mailsender:
  image: mailsender
  build:
   context: ./src/Exadel.CrazyPrice
   dockerfile: Exadel.CrazyPrice.Services/Mail/MailSenderMailKit/Dockerfile
  ports:
   - 7000:80
  volumes:
   - ./volumes/logs/mailsender:/app/Logs/
   - type: bind
     source: ./volumes/configuration/mailsender/appsettings.Docker.json
     target: /app/appsettings.Docker.json
  environment:
   - ASPNETCORE_URLS=http://+
   - ASPNETCORE_ENVIRONMENT=Docker
  links:
   - cprabbit

 identityserver:
  image: identityserver
  build:
   context: ./src/Exadel.CrazyPrice
   dockerfile: Exadel.CrazyPrice.IdentityServer/Dockerfile
  ports:
   - 8000:80
   - 8001:443
  volumes:
   - ./volumes/logs/identityServer:/app/Logs/
   - ./src/Exadel.CrazyPrice/Exadel.CrazyPrice.IdentityServer:/root/IdentityServer:cached
   - type: bind
     source: ./volumes/certificates/aspnetapp-root-cert.cer
     target: /https-root/aspnetapp-root-cert.cer
   - type: bind
     source: ./volumes/certificates/aspnetapp-identity-server.pfx
     target: /https/aspnetapp-identity-server.pfx
   - type: bind
     source: ./volumes/configuration/identity/appsettings.Docker.json
     target: /app/appsettings.Docker.json
  environment:
   - ASPNETCORE_URLS=https://+;http://+
   - ASPNETCORE_HTTPS_PORT=8001
   - ASPNETCORE_ENVIRONMENT=Docker
   - ASPNETCORE_Kestrel__Certificates__Default__Password=password
   - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp-identity-server.pfx
  links:
   - database
  depends_on:
   - database
   - databaseseed

 webapi:
  image: webapi
  build:
   context: ./src/Exadel.CrazyPrice
   dockerfile: Exadel.CrazyPrice.WebApi/Dockerfile
  ports:
   - 9000:80
   - 9001:443
  volumes:
   - ./volumes/logs/api:/app/Logs/
   - ./src/Exadel.CrazyPrice/Exadel.CrazyPrice.WebApi:/root/Api:cached
   - type: bind
     source: ./volumes/certificates/update-ca-cert.sh
     target: /https-root/update-ca-cert.sh 
   - type: bind
     source: ./volumes/certificates/aspnetapp-root-cert.cer
     target: /https-root/aspnetapp-root-cert.cer
   - type: bind
     source: ./volumes/certificates/aspnetapp-web-api.pfx
     target: /https/aspnetapp-web-api.pfx
   - type: bind
     source: ./volumes/configuration/api/appsettings.Docker.json
     target: /app/appsettings.Docker.json
  environment:
   - ASPNETCORE_URLS=https://+;http://+
   - ASPNETCORE_HTTPS_PORT=9001
   - ASPNETCORE_ENVIRONMENT=Docker
   - ASPNETCORE_Kestrel__Certificates__Default__Password=password
   - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp-web-api.pfx   
  entrypoint: bash -c "/https-root/update-ca-cert.sh && dotnet Exadel.CrazyPrice.WebApi.dll"
  links:
   - database
   - identityserver
  depends_on:
   - database
   - databaseseed
   - identityserver